game/urls.py
from django.urls import path, include
from . import views

app_name = 'game'
urlpatterns = [
    path('', views.GameList.as_view(), name='game-home'),
    path('statistics', views.Statistics.as_view(), name='game-stats'),
    path('live', views.GameList.as_view(), name='game-scores'),
    path('game/<int:pk>/', views.GameView.as_view(), name='game-view'),
    path('player/<int:slug>/', views.PlayerView.as_view(), name='player-view'),
    path('server/<int:pk>/', views.GameServerView.as_view(), name='server-view'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html prefix="og: https://ogp.me/hs#">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block meta %}
  <title> tce stats </title>
  {% endblock %}
  {% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
  {% endblock %}

  {% block scripts_head %}
    <script type="text/javascript" src="{% static 'js/game.js' %}"> </script>
    <script type="text/javascript" src="{% static 'js/mobile-toggle.js' %}"> </script>
  {% endblock %}

</head>
<body class="dark-blue">
  <div id="page">
  {% block page %}
    <nav> 
    {% block navigation %}
      <a href="{% url 'game:game-scores' %}"> Scores </a>
      <a href="{% url 'game:game-stats' %}"> Statistics </a>
    {% endblock %}
    </nav> 
  {% endblock %}
  </div>
  <!-- pre> {# % debug % #} </pre -->
  <!-- pre> {# {inspect} #} </pre -->
</body>
</html>

templates/discord.html
<iframe class="discord" 
src="https://discord.com/widget?id=831098936126734336&theme=dark" 
width="100%" height="500" allowtransparency="true" frameborder="0" 
sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts">
</iframe>

templates/form.html
<form class="dark-gray" name="game-browser" method="get">
  {{ form.as_p }}
  <input type="submit" value="{{form.submit_label}}">
  <a href="."> Clear </a>
</form>

templates/navigation.html
<nav> 
  <a href="{% url 'game:game-scores' %}"> Scores </a>
  <a href="{% url 'game:game-stats' %}"> Statistics </a>
  <label> Switch to :
    <select>
      <option selected value="scores"> Scores </option> 
      <option value="stats"> Statistics </option>
    </select>
  </label>
</nav>

templates/page-sidebars.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'css/three-columns.css' %}" />
{% endblock %}

{% block page %}
  <nav>
  {% block navigation %}
    {{ block.super }}
    <label> Switch to :
      <select>
        <option value="1"> {{ first_title |default:"First" }} </option> 
        <option selected value="2"> {{ main_title |default:"Main" }} </option> 
        <option value="3"> {{ second_title |default:"Second" }} </option>
      </select>
    </label>
  {% endblock %}
  </nav>
  <aside class="first not-shown">
    {% block sidebar_first %}
    {% endblock %}
  </aside>
  <main>
    {% block main %}
    {% endblock %}
  </main>
  <aside class="second not-shown">
    {% block sidebar_second %}
      {# include 'discord.html' #}
    {% endblock %}
  </aside>
{% endblock page %}

templates/page.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'css/two-columns.css' %}" />
{% endblock styles %}

{% block page %}
  <nav>
  {% block navigation %}
    {{ block.super }}
    <label> Switch to :
      <select>
        <option selected value="1"> {{ main_title |default:"Main" }} </option> 
        <option value="2"> {{ side_title |default:"Sidebar" }} </option>
      </select>
    </label>
  {% endblock %}
  </nav>

  <main>
  {% block main %}
  {% endblock %}
  </main>

  <aside class="not-shown">
  {% block sidebar %}
    {# include 'discord.html' #}
  {% endblock %}
  </aside>
{% endblock page %}

templates/pager.html
<nav class="pager">
  <ul>
  {% if page.has_previous %}
    <li> <a href = "?{{ previous_page_params }}"> previous 
    </a> </li>
  {% endif %}
  <li> page {{ page.number }} out of {{ page.paginator.num_pages }} </li>
  {% if page.has_next %}
    <li> <a href = "?{{ next_page_params }}"> next 
    </a> </li>
  {% endif %}

  </ul>
</nav>